---
# OS Configuration for HANA Playbook
- hosts: hanaserver
  remote_user: root
#  collections: ansible-base
  tasks:
    - name: Add an Ethernet connection with static IP configuration
      community.general.nmcli:
        conn_name: "{{ item.vnic }}"
        type: ethernet
        ip4: "{{ item.ipv4 }}"
        gw4: "{{ item.gw4 | default(omit) }}"
        dns4: "{{ item.dns4 | default(omit) }}"
        mtu: "{{ item.mtu | default(9000) }}"
        state: present
      loop: "{{ ip_list }}" 
