---
# OS Configuration for HANA Playbook
- hosts: hanaserver
  remote_user: root
#  collections: ansible-base
  tasks:
    - name: Set hostname
      command: 'hostnamectl set-hostname "{{ hana_hostname_short }}"'
