---
# OS Configuration for HANA Playbook
- hosts: hanaserver
  remote_user: root
#  collections: ansible-base
  tasks:
    - name: Change the permission on mounted NFS
      file:
        path: "{{ item }}"
        recurse: yes
        owner: root
        group: root
        state: directory
        mode: '0777'
      loop: 
         - "/hana/data"
         - "/hana/log"
         - "/hana/shared"

    - name: Copy idmap.conf file from config_files to each host
      copy:
        src: config_files/idmapd.conf
        dest: /etc/idmapd.conf
        owner: root
        group: root
        mode: '0644'
        backup: yes

    - name: Start and enable idmap service
      service:
        name: nfs-idmapd
        state: started
        enabled: yes

    - name: Mount the NFS Volumes for HANA
      mount:
        src: "{{ item.ntap_vol_name }}"
        path: "{{ item.mount_path }}"
        fstype: nfs
        opts: 'rw,bg,vers=4,minorversion=1,hard,timeo=600,rsize=1048576,wsize=1048576,intr,noatime,lock'
        state: mounted
        backup: yes
      loop: "{{ mount_list }}" 
