---
# CI SAP HANA Playbook
- hosts: ucs
  connection: local
  collections:
  - cisco.ucs
  gather_facts: no
  tasks:
    - name: UCS Chassis Discovery Policy
      ucs_managed_objects:      
        hostname: "{{ ucs_hostname }}"
        username: "{{ ucs_username }}"
        password: "{{ ucs_password }}"
        state: "{{ ucs_state }}"
        objects:      
        - {
           "module": "ucsmsdk.mometa.compute.ComputeChassisDiscPolicy",
           "class": "ComputeChassisDiscPolicy",
           "properties": {
              "parent_mo_or_dn": "org-root",
              "action": "4-link",
              "link_aggregation_pref": "port-channel"
                         }
          }
