---
# CI SAP HANA Playbook
- hosts: ucs
  connection: local
  collections:
  - cisco.ucs
  gather_facts: no
  tasks:
    - name: UCS System QoS Class Platinum
      ucs_system_qos:
        hostname: "{{ ucs_hostname }}"
        username: "{{ ucs_username }}"
        password: "{{ ucs_password }}"
        priority: 'platinum'
        admin_state: 'enabled'
        multicast_optimize: 'no'
        weight: '10'
        cos: '5'
        mtu: '9216'
