---
# CI SAP HANA Playbook
- hosts: ucs
  connection: local
  collections:
  - cisco.ucs
  gather_facts: no
  tasks:
    - name: Configure Compute PSU policy
      ucs_managed_objects:
        hostname: "{{ ucs_hostname }}"
        username: "{{ ucs_username }}"
        password: "{{ ucs_password }}"
        state: "{{ ucs_state }}"
        objects:
        - module: ucsmsdk.mometa.compute.ComputePsuPolicy
          class: ComputePsuPolicy
          properties:
             parent_mo_or_dn: org-root
             redundancy: grid
