---
# CI SAP HANA Playbook
- hosts: ucs
  connection: local
  collections:
  - cisco.ucs
  gather_facts: no
  tasks:
    - name: Create Local Disk Configuration Policy
      ucs_managed_objects:
        hostname: "{{ ucs_hostname }}"
        username: "{{ ucs_username }}"
        password: "{{ ucs_password }}"
        state: "{{ ucs_state }}"
        objects:
        - module: ucsmsdk.mometa.storage.StorageLocalDiskConfigPolicy
          class: StorageLocalDiskConfigPolicy
          properties:
             parent_mo_or_dn: org-root
             name: "{{ var_local_disk }}"
             descr: Local disk RAID1 for OS
             mode: raid-mirrored
             protect_config: 'no'
