---
# CI SAP HANA Playbook
- hosts: ucs
  connection: local
  collections:
  - cisco.ucs
  gather_facts: no
  tasks:
  - name: Create QoS Policy Platinum
    ucs_managed_objects: 
      hostname: "{{ ucs_hostname }}"
      username: "{{ ucs_username }}"
      password: "{{ ucs_password }}"
      state: "{{ ucs_state }}"
      objects:      
        - {
            "module": "ucsmsdk.mometa.epqos.EpqosDefinition",
            "class": "EpqosDefinition",
            "properties": {
                "parent_mo_or_dn": "org-root",                
                "name": "{{ var_qos_policy_name }}"
            },
            "children": [
                {
                    "module": "ucsmsdk.mometa.epqos.EpqosEgress",
                    "class": "EpqosEgress",
                    "properties": {
                        "prio": "platinum"
                    }
                }
            ]
          }   
