---
# CI SAP HANA Playbook
- hosts: ucs
  connection: local
  collections:
  - cisco.ucs
  gather_facts: no
  tasks:
  - name: Create vNIC/vHBA Placement Policy
    ucs_managed_objects: 
      hostname: "{{ ucs_hostname }}"
      username: "{{ ucs_username }}"
      password: "{{ ucs_password }}"
      state: "{{ ucs_state }}"
      objects:      
        - {
            "module": "ucsmsdk.mometa.fabric.FabricVConProfile",
            "class": "FabricVConProfile",
            "properties": {
                "parent_mo_or_dn": "{{ var_org }}",
                "name": "{{ var_vnic_placement_name }}",
                "mezz_mapping": "linear-ordered"                
            }
          }   
