---
# CI SAP HANA Playbook
- hosts: ucs
  connection: local
  collections:
  - cisco.ucs
  gather_facts: no
  tasks:
    - name: Queries UCS Manager objects by class or distinguished name
      ucs_query:
        hostname: "{{ ucs_hostname }}"
        username: "{{ ucs_username }}"
        password: "{{ ucs_password }}"
        delegate_to: localhost
        distinguished_names: '{{ var_org }}/ls-{{ var_sp_scale_out_name1 }}/ipv4-pooled-addr'
      register: mgmt_ip
    - debug:
        var: mgmt_ip.objects['{{ var_org }}/ls-{{ var_sp_scale_out_name1 }}/ipv4-pooled-addr']['addr']
#        var: mgmt_ip
#        verbosity: 3
