---
# CI SAP HANA Playbook
- hosts: ucs
  connection: local
  gather_facts: no
  tasks:
    - name: Queries UCS Manager objects by class or distinguished name
      ucs_query:
        hostname: "{{ ucs_hostname }}"
        username: "{{ ucs_username }}"
        password: "{{ ucs_password }}"
        delegate_to: localhost
        class_ids: VnicLun
#        distinguished_names: org-root/org-T02-HANA/ls-HANA-ScaleUp-01/iscsi-boot-params/boot-vnic-iSCSI-Boot-A/2/lun
